name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip
        run: zip -r repro-1-randomizers.zip Randomizers/ README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: repro-1-randomizers.zip
          token: ${{ secrets.TOKEN }}
        env:
          GITHUB_REPOSITORY: drzhnn/repro-1-randomizers